"""Unified router for local Ollama models with ordered fallback."""

from typing import List, Optional

import requests

from config.settings import settings


SUPPORTED_MODELS = ["mistral", "phi3", "gemma:2b"]


def _build_priority(model_name: Optional[str]) -> List[str]:
    requested = (model_name or "").strip()
    if requested in SUPPORTED_MODELS:
        return [requested] + [model for model in SUPPORTED_MODELS if model != requested]
    return SUPPORTED_MODELS.copy()


def generate_response(
    prompt: str,
    model_name: Optional[str] = "mistral",
    timeout: int = 30,
    use_fallback: bool = True,
) -> str:
    """
    Generate a response using Ollama with optional ordered fallback.

    Fallback order:
    1) mistral
    2) phi3
    3) gemma:2b
    """
    if not isinstance(prompt, str) or not prompt.strip():
        raise ValueError("prompt must be a non-empty string")

    if use_fallback:
        candidate_models = _build_priority(model_name)
    else:
        selected = (model_name or "mistral").strip()
        candidate_models = [selected]

    last_error: Optional[Exception] = None

    for model in candidate_models:
        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False,
        }

        try:
            response = requests.post(settings.OLLAMA_URL, json=payload, timeout=timeout)
            response.raise_for_status()
            data = response.json()
            text = str(data.get("response", "")).strip()
            if text:
                return text
        except requests.RequestException as exc:
            last_error = exc
            continue

    if last_error:
        raise last_error
    raise RuntimeError("No response generated by the configured models")
